In [2]:
import tensorflow as tf
import numpy as np

In [22]:
from sklearn.metrics import confusion_matrix


In [7]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epochs,logs={}):
    if(logs.get('accuracy')>0.99):
      print("Reached the accuracy of 99 so stopping the training")
      self.model.stop_training = True

In [14]:

callbacks = myCallback()

mnist= tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)= mnist.load_data()

x_train = x_train/255.0
x_test = x_test/255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(units = 128 , activation= tf.nn.relu),
    tf.keras.layers.Dense(units = 512 , activation  = tf.nn.relu),
    tf.keras.layers.Dense(units = 10 , activation = tf.nn.softmax),
])

model.compile(optimizer='adam',
                loss= 'sparse_categorical_crossentropy',
                metrics = ['accuracy'])
  
model.fit(x_train, y_train , epochs=10 , callbacks = [callbacks])


Epoch 1/10
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2186 - accuracy: 0.9340
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0918 - accuracy: 0.9717
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0661 - accuracy: 0.9791
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0496 - accuracy: 0.9843
Epoch 5/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0396 - accuracy: 0.9872
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0311 - accuracy: 0.9899
Epoch 7/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0274 - accuracy: 0.9906


In [16]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.1016 - accuracy: 0.9759


[0.10164982825517654, 0.9758999943733215]

In [17]:
pred = model.predict(x_test)

In [18]:
pred[0]

array([1.8642177e-09, 2.5023834e-07, 1.5267061e-07, 8.7813781e-08,
       1.2995392e-08, 1.7628121e-09, 1.0339626e-12, 9.9999368e-01,
       3.9459014e-09, 5.8316400e-06], dtype=float32)

In [19]:
y_test[0]

7

Confusion matrix

In [30]:
from sklearn.metrics import confusion_matrix
import numpy as np

confusion = confusion_matrix(y_test, np.argmax(pred , axis=1))

In [31]:
print (confusion)

[[ 976    0    1    0    0    0    3    0    0    0]
 [   4 1125    3    0    0    1    2    0    0    0]
 [   1    1 1020    1    1    0    2    4    1    1]
 [   2    1    2  994    0    3    0    3    1    4]
 [   1    0    1    0  955    0    8    1    1   15]
 [   2    0    0    9    1  873    2    1    1    3]
 [   7    2    1    1    3    6  938    0    0    0]
 [   2    6    8    2    1    0    0  994    1   14]
 [  20    0   23   10    2   11    7    2  889   10]
 [   0    3    0    2    4    3    0    2    0  995]]
